import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 수동으로 사이드바 구성 - 보호된 섹션은 외부 링크로 설정
  tutorialSidebar: [
    'intro', // Public Docs
    {
      type: 'link',
      label: '💼 Workspace',
      href: 'https://shusworkspace-auth.shusworkspace.workers.dev/docs/workspace/',
    },
    {
      type: 'link',
      label: '🔒 Private Notes',
      href: 'https://shusworkspace-auth.shusworkspace.workers.dev/docs/private/',
    },
    {
      type: 'link',
      label: '🚀 Project A',
      href: 'https://shusworkspace-auth.shusworkspace.workers.dev/docs/project-a/',
    },
    {
      type: 'link',
      label: '🚀 Project C',
      href: 'https://shusworkspace-auth.shusworkspace.workers.dev/docs/project-c/',
    },
    // Tutorial 섹션 (기존 Docusaurus 기본 내용 - autogenerated)
    {
      type: 'autogenerated',
      dirName: 'tutorial-basics'
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-extras'
    }
  ],
};

export default sidebars;
