name = "shusworkspace-auth"
main = "auth-worker.js"
compatibility_date = "2024-01-01"
account_id = "ea3ba8126f79af0b8a1bc1a057a6a7f1"

# GitHub Pages URL을 Workers Routes에 설정
# 실제 배포 시에는 아래 domain을 실제 도메인으로 변경하세요
# routes = [
#   { pattern = "shiwookim.github.io/sws/*", zone_name = "your-domain.com" }
# ]
